/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        surface: '#0b1326',
        'surface-dim': '#0b1326',
        'surface-bright': '#31394d',
        'surface-variant': '#2d3449',
        'surface-container-lowest': '#060e20',
        'surface-container-low': '#131b2e',
        'surface-container': '#171f33',
        'surface-container-high': '#222a3d',
        'surface-container-highest': '#2d3449',
        'on-surface': '#dae2fd',
        'on-surface-variant': '#cbc3d7',
        background: '#0b1326',
        'on-background': '#dae2fd',
        primary: '#d0bcff',
        'on-primary': '#3c0091',
        'primary-container': '#a078ff',
        'on-primary-container': '#340080',
        'primary-fixed': '#e9ddff',
        'primary-fixed-dim': '#d0bcff',
        'on-primary-fixed': '#23005c',
        'inverse-primary': '#6d3bd7',
        secondary: '#adc6ff',
        'on-secondary': '#002e6a',
        'secondary-container': '#0566d9',
        'on-secondary-container': '#e6ecff',
        'secondary-fixed': '#d8e2ff',
        tertiary: '#cebdff',
        'tertiary-container': '#9b7fed',
        error: '#ffb4ab',
        'error-container': '#93000a',
        outline: '#958ea0',
        'outline-variant': '#494454',
      },
      fontFamily: {
        sans: ['Manrope', 'Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
};
